### PR TITLE
Fix driver input buffers while disabled

### PR DESCRIPTION
**Pull request by hyperliskdev**
## Solution
Used proposed solution in issue #2 

Added a method to `SubsystemLooper` called `stopAll()`. This method iterates through each registered subsystem, and calls each `stop()` method.

`m_subsystemLooper.stopAll()` is now called upon enabling the robot.

### CODE REVIEW

**Comment by ewpratten** [comment]
This fix does not seem to entirely solve the problem (as demonstrated during testing).

Thinking about the problem again, the reason we are still seeing movement after enabling is due to the fact that `DriveTrain` is not buffered. 

To solve this, we should add a way to kill all `CommandGroup`s (but not normal `Command`s).

**Comment by ewpratten** [comment]
Maybe this can be done with the [Scheduler](https://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/command/Scheduler.html)?

If not, we could create a "watcher", where we register all autonomous `CommandGroup`s? This class would then have it's own `stopAll()` method that only stops autonomous commands. With this, starting something like hatch placement (an autonomous sequence) while disabled, would be automatically cancelled?

A simpler (but messier) approach would be to disallow some actions by checking `DriverStation.isEnabled()` ( [documentation](https://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/DriverStation.html) ). A pseudocoded example for intake would be:

```java
void execute(){
    // Get driver inputs
    ...

    // Only start hatch placement if bot is enabled
    if (DriverStation.isEnabled()){
    
    // Code to control bot goes here
    ...

    }
}
```

**Review by ewpratten — CHANGES_REQUESTED** [review]
Stop `CommandGroup` execution while disabled

**Review by ewpratten — APPROVED** [review]

**Comment by ewpratten** [comment]
Please test this on HATCHfield ( following same instrucitons from #2 ), and report back with results.

**Comment by ewpratten** [comment]
Results of today's testing:

 - None of the proposed fixes solved the problem
 - We concluded that the problem is caused by buffering of commands and / or HID devices

**Comment by Ewpratten** [comment]
@awpratten has been assigned to review the code

**Comment by ewpratten** [comment]
@awpratten and I just discovered `Command.setRunWhenDisabled​()` ( [documentation](https://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/command/Command.html#setRunWhenDisabled(boolean)) ). This may be useful to solve this issue.

If we set `IntakeControl` to run while the bot is disabled, then go back to checking `DriverStation.getInstance().isEnabled()` when the button is pressed, we could discard any button inputs while the bot is disabled. This should stop the `GommandGroup` from running/

Pseudocode:
```java
// Robot.java

void robotInit(){
    m_intakeControl.setRunWhenDisabled​(true); // Allow running while disabled
}

```

```java
// IntakeControl.java

void execute(){
    // Get driver inputs
    ...
    m_shouldOuttake = getButton();

    // Only start hatch placement if bot is enabled
    if (DriverStation.isEnabled()){
    
    // Code to control bot goes here
    ...

    } else {
        // Discard m_shouldOuttake when robot is disabled
        m_shouldOuttake = false;

    }
}

```

Thoughts?

**Comment by hyperliskdev** [comment]
I don't see why we shouldn't try it out. The docs say that commands will get cancelled by default in disabled mode. We should also checkout what is happening when the command is cancelled. Let try it.

**Comment by ewpratten** [comment]
Looking good! Let's just remove the old code before merge

**Comment by ewpratten** [comment]
Perfect! Will merge

**Pull request merged**
